### ISSUE TITLE
Equation checking using color-by-numbers

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath-solver#6]

**Comment by sachingrover211** [comment]
@jonwetzel this has to be part of topomath. Evaluation is not part of the solver. There might be very little to no changes in solver for this.

**Comment by jonwetzel** [comment]
Issue moved to [Dragoon-Lab/topomath #243](https://github.com/Dragoon-Lab/topomath/issues/243) via [**ZenHub**](https://www.zenhub.com/)
